"""Test create table

Revision ID: baa6de2da768
Revises: 1506a40f1d20
Create Date: 2025-09-07 13:55:12.378806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'baa6de2da768'
down_revision: Union[str, Sequence[str], None] = '1506a40f1d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('todo', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('is_completed', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('create_date', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__todo__3213E83F54D333F2'))
    )
    # ### end Alembic commands ###
